axonivy/dataclass-editor

packages/dataclass-editor/src/happy-pipeline.test.ts
Give the pipeline a test to report on to make it happy.
=> XIVY-12288 make pipeline happy

README.md, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/dataclass-client-mock.ts, integrations/standalone/src/url-helper.ts, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.css, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/index.ts, packages/dataclass-editor/src/protocol/ClientContextProvider.tsx, packages/dataclass-editor/src/protocol/client-json-rpc.ts, packages/dataclass-editor/src/protocol/index.ts, packages/dataclass-editor/src/protocol/types.ts, packages/dataclass-editor/src/query/QueryProvider.tsx, packages/dataclass-editor/src/query/index.ts, packages/dataclass-editor/src/query/query-client.ts
Should we also move stuff like
- `url-helper.ts`
- `ClientContextProvider.tsx`
- `client-json-rpc.ts`
- `protocol/types.ts`
- `query-client.ts`
- etc.
to `ui-components`?
=> XIVY-12288 display data class data as string

packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx
feature is implemented by selecting `Business Data Class` under `Class type`
=> XIVY-12288 remove business case data annotation

integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/Button.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/Settings.ts, integrations/standalone/tests/pageobjects/Switch.ts, integrations/standalone/tests/pageobjects/Theme.ts, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/happy-pipeline.test.ts
add tests for theme and detail toggle
remove `happy-pipeline.test.ts`
=> XIVY-12288 add some mock tests

integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-entityclass.spec.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/Table.ts, packages/dataclass-editor/src/components/dataclass/master/DataClassMasterContent.tsx
=> XIVY-12288 remove persistent from table

packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/context/AppContext.tsx, packages/dataclass-editor/src/utils/lambda/lambda.ts
`AppContext` now contains function `setDataClass` to save data class.
=> XIVY-12289 add mutation to save data class

integrations/standalone/src/index.tsx, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.css, packages/dataclass-editor/src/protocol/client-json-rpc.ts
https://github.com/axonivy/ui-components/pull/150
=> XIVY-14729 Add websocket reconnect

integrations/standalone/pom.xml, integrations/standalone/tests/screenshots/pom.xml
Raising the version does not touch all pom.xml 
Can you fix that @ivy-lgi 
I did it manually now so that the re-integration do work.
=> Raise to v12 manually

integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-entityclass.spec.ts, integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/Detail.ts, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/components/dataclass/data/dataclass-utils.test.ts, packages/dataclass-editor/src/components/dataclass/data/dataclass-utils.ts, packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx, packages/dataclass-editor/src/components/dataclass/master/DataClassMasterToolbar.tsx
- Remove the word "class" from headers and class type selection.
- Improve adjustment of headers to class type.
=> XIVY-12288 improve class type naming

integrations/standalone/src/mock/dataclass-client-mock.ts, integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/ClassType.ts, integrations/standalone/tests/pageobjects/Detail.ts, packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx
=> XIVY-12291 edit data class properties

packages/dataclass-editor/src/DataClassEditor.tsx
=> Show error if data class couldn't be loaded

integrations/standalone/src/mock/dataclass-client-mock.ts, integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-entityclass.spec.ts, integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/Collapsible.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/Detail.ts, integrations/standalone/tests/pageobjects/Table.ts, packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx, packages/dataclass-editor/src/components/dataclass/detail/FieldDetailContent.tsx
=> XIVY-12288 hide complex properties in collapsibles

integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-entityclass.spec.ts, integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/Detail.ts, packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx, packages/dataclass-editor/src/components/dataclass/detail/FieldDetailContent.tsx
=> Xivy 12288/combine collapsibles

package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/components/dataclass/detail/FieldDetailContent.tsx
- Use BasicInput for controlled value state
- Use key on full detail content and only selection, otherwise you cannot change the name
Same problem as: https://github.com/axonivy/config-editor-client/pull/171
Before:
After:
=> XIVY-15025 Fix input cursor jump to end

integrations/standalone/tests/integration/dataclass-editor-business-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-dataclass.spec.ts, integrations/standalone/tests/integration/dataclass-editor-entityclass.spec.ts, integrations/standalone/tests/mock/dataclass-editor.spec.ts, integrations/standalone/tests/pageobjects/AddFieldDialog.ts, integrations/standalone/tests/pageobjects/Annotations.ts, integrations/standalone/tests/pageobjects/Button.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/Detail.ts, integrations/standalone/tests/pageobjects/Settings.ts, integrations/standalone/tests/pageobjects/Table.ts, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/components/dataclass/detail/AnnotationsTable.tsx, packages/dataclass-editor/src/components/dataclass/detail/DataClassDetailContent.tsx, packages/dataclass-editor/src/components/dataclass/detail/FieldDetailContent.tsx
=> XIVY-12288 annotations table

packages/dataclass-editor/src/master/DataClassMasterContent.css, packages/dataclass-editor/src/master/DataClassMasterContent.tsx
See https://github.com/axonivy/config-editor-client/pull/172
=> use better deselect approach

integrations/standalone/tests/integration/jump-to-editors.spec.ts, integrations/standalone/tests/mock/editor.spec.ts, packages/dataclass-editor/src/DataClassEditor.test.ts, packages/dataclass-editor/src/DataClassEditor.tsx
As requested by bruno
Before:
After:
=> change header titles

packages/dataclass-editor/src/master/DataClassMasterContent.test.ts, packages/dataclass-editor/src/master/DataClassMasterContent.tsx
=> fix `simpleTypeName`

integrations/standalone/tests/integration/entityclass.spec.ts, integrations/standalone/tests/integration/validation.spec.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, packages/dataclass-editor/src/master/DataClassMasterContent.css, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/ValidationRow.test.ts, packages/dataclass-editor/src/master/ValidationRow.tsx, packages/dataclass-editor/src/master/useValidation.test.ts, packages/dataclass-editor/src/master/useValidation.ts
Not completely sure where to put these messages. Any suggestions?
=> XIVY-14998 add validation messages of class

integrations/standalone/tests/mock/master.spec.ts, packages/dataclass-editor/src/master/AddFieldDialog.tsx
=> make new fields persistent by default

integrations/standalone/tests/mock/master.spec.ts, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/master/AddFieldDialog.tsx
- Shortcut `Ctrl+Alt+N` to open the add dialog
- Support pressing `Enter` to confirm the dialog
- Add a tooltip on the add button to show the shortcut
- Add a description to the dialog for accessibility
=> XIVY-15138 add fields by keyboard

packages/dataclass-editor/src/detail/field/browser/useTypeBrowser.tsx
=> XIVY-15045 Move TypeAsList-Checkbox into the footer

integrations/standalone/tests/mock/master.spec.ts, integrations/standalone/tests/pageobjects/AddFieldDialog.ts, integrations/standalone/tests/pageobjects/DataClassEditor.ts, integrations/standalone/tests/pageobjects/abstract/Combobox.ts, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/detail/field/ComboboxFieldWithTypeBrowser.css, packages/dataclass-editor/src/detail/field/ComboboxFieldWithTypeBrowser.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx
=> XIVY-15045 Add Type-Combobox to Add DataClass-Dialog

integrations/standalone/package.json, package-lock.json, packages/dataclass-editor/package.json, playwright/tests/integration/mock/detail-field-entity-association.spec.ts
Adjust to ui-components change that treats undefined as empty item.
=> XIVY-15134 consider empty item

packages/dataclass-editor/src/detail/field/entity/FieldEntityAssociation.test.ts, packages/dataclass-editor/src/detail/field/entity/FieldEntityAssociation.tsx, playwright/tests/integration/mock/detail-field-entity-association.spec.ts, playwright/tests/pageobjects/abstract/FieldMessage.ts, playwright/tests/pageobjects/field/entity/FieldAssociation.ts
=> warn from using one-to-many association

integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/package.json
- Add r19 as peerDep
- Update dependencies
=> Pre work for React v19 support

packages/dataclass-editor/src/context/AppContext.tsx, packages/dataclass-editor/src/context/test-utils/test-utils.tsx, packages/dataclass-editor/src/detail/dataclass/DataClassDetailContent.tsx, packages/dataclass-editor/src/detail/field/FieldDetailContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, playwright/tests/integration/hidden-fields.spec.ts
=> XIVY-15662 Hide type switch on hd data editor

integrations/standalone/package.json, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, playwright/tests/integration/mock/master.spec.ts, playwright/tests/pageobjects/abstract/Table.ts
You can also have a look at this PR after Cool Stuff
=> XIVY-13545 Add Navigation via ArrowKey in Tables

packages/dataclass-editor/src/detail/dataclass/entity/EntityClassDatabaseTable.tsx, packages/dataclass-editor/src/detail/field/entity/FieldEntityDatabaseField.tsx
master https://github.com/axonivy/dataclass-editor-client/pull/119
=> Fix cursor jumps at end of input > R12

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/dataclass-client-mock.ts, package-lock.json, package.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/detail/field/InputFieldWithTypeBrowser.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, packages/dataclass-editor/src/master/ValidationRow.tsx, packages/dataclass-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/mock/master.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/AddFieldDialog.ts, playwright/tests/pageobjects/DataClassEditor.ts, playwright/tests/pageobjects/console-log.ts
**Shortcuts**
Global:
- F1: Open help
- P: Open process (if hd class)
- F: Open form (if hd class)
- A: Add new attribute (hold ctrl/cmd while submit keep it open)
- 1-3: Jump focus (toolbar, main, inscription)
On table:
- Delete: delete selected rows
- C: combine selected rows
**Other stuff**
- Add tests for readonly mode
- Add tests for hotkeys
- Disable reorder on readonly
=> XIVY-15630 Add shortcuts

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/dataclass-client-mock.ts, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/detail/field/InputFieldWithTypeBrowser.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, packages/dataclass-editor/src/master/ValidationRow.tsx, packages/dataclass-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/mock/master.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/AddFieldDialog.ts, playwright/tests/pageobjects/DataClassEditor.ts, playwright/tests/pageobjects/console-log.ts
Global:
- F1: Open help
- P: Open process (if hd class)
- F: Open form (if hd class)
- A: Add new attribute (hold ctrl/cmd while submit keep it open)
- 1-3: Jump focus (toolbar, main, inscription)
On Table:
- Delete: delete selected rows
- C: combine selected rows
*Other stuff*
- Add tests for readonly mode
- Add tests for hotkeys
- Disable reorder on readonly
master: https://github.com/axonivy/dataclass-editor-client/pull/122
=> XIVY-15630 Add shortcuts > R12

packages/dataclass-editor/src/master/AddFieldDialog.tsx
https://github.com/axonivy/dataclass-editor-client/pull/124
=> XIVY-15630 Use known hotkey from object

packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx
Cherry-Pick from https://github.com/axonivy/dataclass-editor-client/pull/126
=> XIVY-13545 Remove unnecessary select-useEffect for main-table

packages/dataclass-editor/src/master/AddFieldDialog.tsx, playwright/tests/pageobjects/AddFieldDialog.ts
https://github.com/axonivy/dataclass-editor-client/pull/129
=> Fix rename create attribute label

packages/dataclass-editor/src/master/DataClassMasterContent.css
master https://github.com/axonivy/dataclass-editor-client/pull/132
=> XIVY-15630 Fix overflow table > R12

packages/dataclass-editor/src/master/DataClassMasterContent.css
same as on the config editor: https://github.com/axonivy/config-editor-client/pull/231
=> XIVY-15630 Fix overflow table

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx
https://github.com/axonivy/dataclass-editor-client/pull/134
=> XIVY-15630 Fix disable hotkeys > R12

packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/context/FieldContext.tsx, packages/dataclass-editor/src/context/test-utils/test-utils.tsx, packages/dataclass-editor/src/detail/Detail.tsx, packages/dataclass-editor/src/detail/field/FieldDetailContent.tsx, packages/dataclass-editor/src/detail/field/FieldNameTypeComment.tsx, packages/dataclass-editor/src/detail/field/FieldProperties.tsx, packages/dataclass-editor/src/detail/field/entity/FieldEntityAssociation.tsx, packages/dataclass-editor/src/detail/field/entity/FieldEntityDatabaseField.tsx
Same as https://github.com/axonivy/dataclass-editor-client/pull/136
=> put validations on field context > 12

packages/dataclass-editor/src/detail/Detail.css, packages/dataclass-editor/src/detail/Detail.tsx
=> make detail scrollable > master

packages/dataclass-editor/src/detail/Detail.css, packages/dataclass-editor/src/detail/Detail.tsx
Same as https://github.com/axonivy/dataclass-editor-client/pull/137
=> make detail scrollable > 12

integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/context/AppContext.tsx, packages/dataclass-editor/src/context/test-utils/test-utils.tsx, packages/dataclass-editor/src/detail/Detail.tsx, packages/dataclass-editor/src/detail/dataclass/DataClassDetailContent.tsx, packages/dataclass-editor/src/detail/dataclass/DataClassType.tsx, packages/dataclass-editor/src/detail/dataclass/entity/EntityClassDatabaseTable.tsx, packages/dataclass-editor/src/detail/dataclass/useDataClassProperty.ts, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/DataClassEditor.ts, playwright/tests/pageobjects/Toolbar.ts
=> XIVY-15630 Undo / Redo 

integrations/standalone/package.json, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/context/AppContext.tsx, packages/dataclass-editor/src/context/test-utils/test-utils.tsx, packages/dataclass-editor/src/detail/Detail.tsx, packages/dataclass-editor/src/detail/dataclass/DataClassDetailContent.tsx, packages/dataclass-editor/src/detail/dataclass/DataClassType.tsx, packages/dataclass-editor/src/detail/dataclass/entity/EntityClassDatabaseTable.tsx, packages/dataclass-editor/src/detail/dataclass/useDataClassProperty.ts, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/DataClassEditor.ts, playwright/tests/pageobjects/Toolbar.ts
https://github.com/axonivy/dataclass-editor-client/pull/141
=> XIVY-15630 Undo / Redo > r12

renovate.json
let's try it here on a npm focused repo. 
let's see what PR we get.
=> Use renovate to automatically update dependencies

package-lock.json
- **Revert "Update dependency eslint to v8.57.1"**
- **Revert "Update dependency @types/node to v22.10.7"**
=> revert renovate updates

integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/detail/Detail.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, packages/dataclass-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts
Change redo hotkey on windows to Ctrl+Y
=> Redo hotkey

integrations/standalone/package.json, package-lock.json, packages/dataclass-editor/package.json, packages/dataclass-editor/src/DataClassEditor.tsx, packages/dataclass-editor/src/detail/Detail.tsx, packages/dataclass-editor/src/master/AddFieldDialog.tsx, packages/dataclass-editor/src/master/DataClassMasterContent.tsx, packages/dataclass-editor/src/master/DataClassMasterToolbar.tsx, packages/dataclass-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts
https://github.com/axonivy/dataclass-editor-client/pull/191
=> Redo hotkey > R12

packages/dataclass-editor/src/master/table/Badge.css, packages/dataclass-editor/src/master/table/Badge.tsx, packages/dataclass-editor/src/master/table/FieldBadges.css, packages/dataclass-editor/src/master/table/FieldBadges.tsx
=> XIVY-15026 beautify badges > master

packages/dataclass-editor/src/master/table/Badge.css, packages/dataclass-editor/src/master/table/Badge.tsx, packages/dataclass-editor/src/master/table/FieldBadges.css, packages/dataclass-editor/src/master/table/FieldBadges.tsx
=> XIVY-15026 beautify badges > 12

integrations/standalone/package.json, package-lock.json, packages/dataclass-editor/package.json
https://github.com/axonivy/dataclass-editor-client/pull/253
=> Move @axonivy packages to peer deps > R12

eslint.config.mjs, integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/src/context/test-utils/test-utils.tsx, playwright/tests/integration/mock/i18n.spec.ts, playwright/tests/pageobjects/DataClassEditor.ts
- config cleanup
- playwright test
=> XIVY-16265 I18n improve

integrations/standalone/src/index.css, packages/dataclass-editor/src/DataClassEditor.css
https://github.com/axonivy/form-editor/pull/498
=> Move ui-components/icons css to integration

.ivy/raise-deps.sh
- therefore shared prettier and eslint-config is left behind
=> fix raise: does not update root package.json > R13.1

packages/dataclass-editor/src/data/type-data.test.ts, packages/dataclass-editor/src/data/type-data.ts, packages/dataclass-editor/src/detail/field/browser/useTypeBrowser.tsx
https://github.com/axonivy/dataclass-editor/pull/426
=> XIVY-16900 Fix type browser translation > R13.1

integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/src/master/AddFieldDialog.tsx
https://1ivy.atlassian.net/browse/XIVY-16606
=> XIVY-1606 Streamline Dialog add Attribute

integrations/standalone/package.json, package-lock.json, package.json, packages/dataclass-editor/src/master/AddFieldDialog.tsx
https://github.com/axonivy/ui-components/pull/544
=> XIVY-16606 Adapt basic dialog changes

.vscode/settings.json, dataclass-editor.code-workspace
https://github.com/axonivy/neo/pull/756
=> Fix ide lint > R12
